### ISSUE TITLE
Web hooks for events should not be added/eletted without/with wrong apikey

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#64]
see on Register a WebHook to event-stream and Unregister a WebHook from event-stream at 36e898068e5d26e82533080c65125c001a4e59db

**Comment by MikeBild** [comment]
Disabled some tests. Some semantic rules about WebHooks.

A) Do not register a WebHook URL that writes to store with the same name as the steam. Because every write creates an "Store-Changed-Event" emitted to a stream with the same name. It created a endless loop. e.g. WebHook on Stream -> Emit Event -> WebHook writes to Store -> Store emits On-Change-Event -> Webhook writes to Store -> endless loop

B) Remove all created stores (created via WebHook) and unregister the registered Webhooks on "afterEach" to isolate the test cases [SHOW](https://github.com/SubKit/subkit-microservice/blob/events_tests/test/integration/event.spec.js#L1327)

Can you enable the other test cases?

**Comment by PerhunAndrey** [comment]
A) I guess so. But may be it would be correct to prevent such situation? because it is a way of hack the server

**Comment by PerhunAndrey** [comment]
>B)
>Can you enable the other test cases?
I'll sort it out today
