### ISSUE TITLE
Web hook does not call provided URL?

### ISSUE THREAD

**Issue by PerhunAndrey** [SubKit/subkit-microservice#65]
see on Register a WebHook to event-stream and Unregister a WebHook from event-stream at 36e8980

**Comment by MikeBild** [comment]
Disabled some tests. Some semantic rules about WebHooks.

A) Do not register a WebHook URL that writes to store with the same name as the steam. Because every write creates an "Store-Changed-Event" emitted to a stream with the same name. It created a endless loop. e.g. WebHook on Stream -> Emit Event -> WebHook writes to Store -> Store emits On-Change-Event -> Webhook writes to Store -> endless loop

B) Remove all created stores (created via WebHook) and unregister the registered Webhooks on "afterEach" to isolate the test cases [SHOW](https://github.com/SubKit/subkit-microservice/blob/events_tests/test/integration/event.spec.js#L1327)

Can you enable the other test cases?

**Comment by PerhunAndrey** [comment]
>B)
>Can you enable the other test cases?
I'll sort it out today
